language: python

python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest
  - cat xamaral-5a06f7cb6cc5.json | docker login -u _json_key --password-stdin https://eu.gcr.io
  - make push
before_install:
  - openssl aes-256-cbc -K $encrypted_5efe748433d5_key -iv $encrypted_5efe748433d5_iv
    -in k8s-ss0.repo.key.enc -out k8s-ss0.repo.key -d
  - sudo apt-get install -y git-crypt
  - git-crypt unlock k8s-ss0.repo.key

