language: python
services:
- docker
python:
- '3.7'
before_install:
- openssl aes-256-cbc -K $encrypted_5efe748433d5_key -iv $encrypted_5efe748433d5_iv
  -in k8s-ss0.repo.key.enc -out k8s-ss0.repo.key -d
- sudo apt-get install -y git-crypt
- git-crypt unlock k8s-ss0.repo.key
install:
- pip install pipenv
- pipenv install --dev
script:
- pytest
deploy:
  provider: script
  script: scripts/push.sh
env:
  global:
  - secure: dFPc1cLTzrLy+kL+4hWUEyZ1lcwfN5qMpqDzbWmq86UDOvez8KjLnceWzZWggth6OJAWqoQGlz926rS+PIMtfvrKEODx3UaxbjnqeQ50GvRvlfwdbMp792FX1k7V+p01NUCnpoDOJ49aLUVjFWzEoWlEJL6EI/jkUKd66M2QSOGT18udaZl47O21wGU+R7ZWgpP5wY15x2PZCJtYfyvNhNFj5QAiWeJYSfTDqb6OhVaKkd5ejxlRC22I+FPEAXkX9tX+9+4WC7tudDJbq7bMxj0ok1cU6aT//j6PcjaLy3k+nhtb6pZNoBR77zl8BHj0bE82GjwL5IxbQTtesjGPZ/gdRDuKFrHZJi+7fwcl9CTbI0+eLbYpIdRbY66o0gYxowgx9D5GfyAgnZnXd5e56mDZCh7RMhstzzwD4BXvCYzex46ZOzMLx4U6VhL6egaOxVzR83UVHYm8kYrmN7YPhrZKhee5ezGXBlFGs8Jpild/RivHJhjKvPVdVaz0lNRPkyDYqdz7HRpEKiOQC8glOpbNXpQWt0yzgld4X01n4Nik8nYH4K91489IrSKTUok8Hzq7bFOTmn73iOTeGlzRpI+/05fak/Da7eSqcGwpRdX4N5OwuBBv3mdXcIrUhJlrn+aFilVjwGjXl9EwhTrp543iIlUYHYU2WvQSVFpF1/Y=
  - secure: WbHR9eqwqy3wylMQf9k8olBTlce/stpFKED0HuXvOaTK2HxU5o4pVBtp3Wzwr3vuH8MmnR9Fr4kIK/b++qxi2DzC7hmmO9XCJe3h223US7zaixOKVbdbHIp8roLMZhUJi3yn7lW5HGjgVMUVjdGz/YGwkn+c9zrn7gPLdj4m8KtIop3P24AJ7505BiKS27FZ6H8EFSvMap57FX8rMQZ/5bfCNNGxQ47Pp6lCUR3wHQgajVdFRHd/2/dwAdBJh7qbUlYIu2LmRvbCMrueeB9ubFKbx0m+b0JRpXj7B8XRZex7mLdnMb6P7O9nB87pAktrS6MERUxxBzo5PJ3+gAnoPDSKFfuJLmK5YXFvCm4U8RDcmfby507niOam3Gv4mHRTDUdXdDUev7kasXaueZT23sJ7QMV639vvc7uhPn5V/cQPnGfMN4yaLq3V7Pljx2ZhrtpwbYdK/kC3ET36JUMQ1m2+PxJSqP6+/0pgkhPd/c1yzTAf2XklSnp19MavVq5WxOAeMg7ja4+0GUoKCS/nHHV/4R7GxYMm9w8jWFrCssXwVNI95oETPFb1WrKlBbT3tNZzLPwzz+LEW1vhVNiRJ5d2AfYGAb1+bRxzOBiqBLgpWjsCcM0ZT3cM9CXBHcPqlO+88Zd9FHF+OE2MWDkaGGTn6mRBdx2tnHP1vDHzyZo=
