language: python
python:
- '3.7'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
before_install:
- openssl aes-256-cbc -K $encrypted_5efe748433d5_key -iv $encrypted_5efe748433d5_iv
  -in k8s-ss0.repo.key.enc -out k8s-ss0.repo.key -d
- |
  curl -L https://github.com/minrk/git-crypt-bin/releases/download/0.6.0/git-crypt > git-crypt
  echo "128817a63de17a5af03fe69241e453436c6c286c86dd37fb70ed9b3bf7171d7d  git-crypt" | shasum -a 256 -c -
  chmod a+x git-crypt
  ./git-crypt unlock k8s-sso.repo.key

